logout:
    pattern: /logout

user:
    resource: "@SMTCUserBundle/Controller/"
    type:     annotation
    prefix:   /

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

examples:
    resource: "@MainBundle/Controller/Example/"
    type:     annotation
    prefix:   /ejemplo

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
