homepage:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'MainBundle:Default:index.html.twig'

examples:
    pattern: /ejemplo/
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'MainBundle:Example\\Default:examples.html.twig'